### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by netflexy** [FabricMC/fabricmc.net#11]
[crash-2022-10-24_14.46.39-server.txt](https://github.com/FabricMC/fabricmc.net/files/9851510/crash-2022-10-24_14.46.39-server.txt)
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2022-10-24 14:46:39
Description: Exception in server tick loop

java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2535 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at net.minecraft.class_3242.method_14354(class_3242.java:87)
	at net.minecraft.class_3176.method_3823(class_3176.java:142)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414)
	... 9 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [carpet.mixins.json:Connection_packetCounterMixin from mod carpet] from phase [DEFAULT] in config [carpet.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 12 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on packetOutCount could not find any targets matching 'Lnet/minecraft/class_2535;method_10764(Lnet/minecraft/class_2596;Lio/netty/util/concurrent/GenericFutureListener;)V' in net.minecraft.class_2535. Using refmap fabric-carpet-refmap.json [PREINJECT Applicator Phase -> carpet.mixins.json:Connection_packetCounterMixin from mod carpet -> Prepare Injections ->  -> handler$zel000$packetOutCount(Lnet/minecraft/class_2596;Lio/netty/util/concurrent/GenericFutureListener;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308)
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:483)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1330)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 12 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.19.1
	Minecraft Version ID: 1.19.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 18.0.2.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 318132232 bytes (303 MiB) / 574619648 bytes (548 MiB) up to 5368709120 bytes (5120 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz
	Identifier: Intel64 Family 6 Model 42 Stepping 7
	Microarchitecture: Sandy Bridge (Client)
	Frequency (GHz): 2.49
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA GeForce GT 525M
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x0df5
	Graphics card #0 versionInfo: DriverVersion=23.21.13.9135
	Graphics card #1 name: Intel(R) HD Graphics 3000
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 2108.00
	Graphics card #1 deviceId: 0x0126
	Graphics card #1 versionInfo: DriverVersion=9.17.10.4459
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 1.33
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 2048.00
	Memory slot #1 clockSpeed (GHz): 1.33
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 7699.94
	Virtual memory used (MB): 4724.28
	Swap memory total (MB): 1664.00
	Swap memory used (MB): 69.13
	JVM Flags: 1 total; -Xmx5G
	Fabric Mods: 
		carpet: Carpet Mod 1.4.82
		carpet-fixes: Carpet Fixes 1.19-1.11.2
			com_github_llamalad7_mixinextras: MixinExtras 0.0.6
			conditional-mixin: conditional mixin 0.3.0
		fabric: Fabric API 0.58.5+1.19.1
			fabric-api-base: Fabric API Base 0.4.9+e62f51a395
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f4095
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.15+d5533c0195
			fabric-command-api-v1: Fabric Command API (v1) 1.2.9+f71b366f95
			fabric-command-api-v2: Fabric Command API (v2) 2.1.5+0c17ea9695
			fabric-commands-v0: Fabric Commands (v0) 0.2.26+df3654b395
			fabric-containers-v0: Fabric Containers (v0) 0.1.31+df3654b395
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.1+07df213e95
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d2495
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4a95
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.5+a680b9b495
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.28+a6d2f78595
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f4095
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f4095
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.26+df3654b395
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+1899036195
			fabric-item-api-v1: Fabric Item API (v1) 1.5.5+35a03c4395
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.26+9ff28f4095
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc73895
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.1+03a4e56895
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.4+9e7660c695
			fabric-message-api-v1: Fabric Message API (v1) 5.0.1+4e0178f495
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.11+33fbc73895
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.1+3082331495
			fabric-networking-v0: Fabric Networking (v0) 0.3.18+df3654b395
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.8+9ff28f4095
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553a95
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.21+23c4cfef95
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f4095
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f4095
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a395
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.6+5f1a85e095
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.10+9ff28f4095
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a395
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c695
		fabricloader: Fabric Loader 0.14.9
		java: Java HotSpot(TM) 64-Bit Server VM 18
		minecraft: Minecraft 1.19.1
		nochatreports: No Chat Reports 1.19.1-v1.8.1
		skinrestorer: Skin Restorer 1.1.0
		voicechat: Simple Voice Chat 1.19.1-2.3.9
	Server Running: true
	Data Packs: vanilla, Fabric Mods
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
